### ISSUE TITLE
.toBeDefined instead of (or in addition to) .toBeTruthy

### ISSUE THREAD

**Issue by cormacmccarthy** [egm0121/jest-test-gen#4]
Currently running `jest-test-gen` on the following:

```
const myFunc = (a, b) => { ... }

export {myFunc}
```

Would generate:
```
import { myFunc } from '../myFile.js';

describe('myFunc', () => {
	it('should expose a function', () => {
		// const retValue = myFunc(a, b);
		expect(false).toBeTruthy();
	});
});
```

But the following would be more useful:
```
import { myFunc } from '../myFile.js';

describe('myFunc', () => {
	it('should expose a function', () => {
		// const retValue = myFunc(a, b);
		expect(myFunc).toBeDefined();
	});
});
```

If you want, you could do:
```
import { myFunc } from '../myFile.js';

describe('myFunc', () => {
	it('should expose a function', () => {
		expect(myFunc).toBeDefined();
	});
	it('should behave as expected', () => {
		// const retValue = myFunc(a, b);
		expect(false).toBeTruthy();
	});
});
```

**Comment by egm0121** [comment]
@cormacmccarthy  I'm not too sure if adding a test for `myFunc.toBeDefined()` actually is more useful, since it was detected to be a function always, otherwise the `describe` block for that function would have not been generated.

What I mean is that if a `it('should expose a function'` block was generated, you are guaranteed that `expect(myFunc).toBeDefined();` will always be `true`

**Comment by egm0121** [comment]
@cormacmccarthy I can see how adding it as a separate test will make it more explicit.👍

btw with the current output if `myFunc` is not a function the test would fail because of a Typerror while running
```
it('should behave as expected', () => {
	const retValue = myFunc(a, b); // if sometime in the future myFunc is no more a function this will throw
	expect(retValue).toBeTruthy();
});
```

**Comment by cormacmccarthy** [comment]
Yep. _and_ you have to actually pass the correct thing in for a & b. It is fine for a stub to get you started, but just not what I need. Which is why I just put the following instead (until I'm ready to actually flesh out the tests):

```
describe('myFunc', () => {
	it('should expose a function', () => {
		expect(myFunc).toBeDefined();
	});
});
```
